# array creation : conversion from other python structures


In [1]:
import numpy as np

In [2]:
listarray = np . array([[1,2,3], [5,8,5], [0,3,1]])

In [3]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [4]:
listarray . dtype

dtype('int32')

In [5]:
listarray . shape

(3, 3)

In [6]:
listarray . size

9

In [7]:
np . array({34,23,23})

array({34, 23}, dtype=object)

In [8]:
zeros = np . zeros((2, 5))

In [9]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
zeros . dtype

dtype('float64')

In [11]:
zeros . shape

(2, 5)

In [12]:
rng = np . arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
lspace = np . linspace(1,5,4)

In [15]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [16]:
emp = np . empty((4,6))

In [17]:
emp

array([[3.56043053e-307, 1.60219306e-306, 7.56571288e-307,
        1.89146896e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.33511018e-306, 6.23057689e-307, 1.33511290e-306,
        1.78019082e-306, 8.45559303e-307, 8.06613465e-308],
       [6.89810244e-307, 1.22387550e-307, 2.22522596e-306,
        8.34423917e-308, 9.79107193e-307, 3.33509775e-317]])

In [18]:
emp_like = np . empty_like(lspace)

In [19]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [20]:
ide = np . identity(45)

In [21]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [22]:
ide . shape

(45, 45)

In [23]:
arr = np . arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])