# welcome to numpy 2

In [1]:
import numpy as np

In [2]:
myarr = np . array([[3, 6, 32, 56]], np . int64)

In [3]:
myarr

array([[ 3,  6, 32, 56]], dtype=int64)

In [4]:
myarr[0]

array([ 3,  6, 32, 56], dtype=int64)

In [5]:
myarr . shape

(1, 4)

In [6]:
myarr . dtype

dtype('int64')

In [7]:
myarr[0, 1] = 45

In [8]:
myarr

array([[ 3, 45, 32, 56]], dtype=int64)

# array creation : conversion from other python structures

In [9]:
listarray = np . array([[1,2,3], [5,8,5], [0,3,1]])

In [10]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [11]:
listarray . dtype

dtype('int32')

In [12]:
listarray . shape

(3, 3)

In [13]:
listarray . size

9