In [14]:
import pandas as pd

In [15]:
import numpy as np

# Numpy Axis

In [16]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [17]:
ar = np . array(x)

In [18]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [19]:
ar . sum(axis=0)

array([12,  8,  9])

In [20]:
ar . sum(axis=1)

array([ 6, 15,  8])

In [21]:
ar . T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [22]:
ar . flat

In [25]:
for item in ar . flat :
    print(item)

1
2
3
4
5
6
7
1
0


In [26]:
ar . ndim

2

In [27]:
one = np . array([1,3,4,634,2])

In [28]:
one . argmax()

3

In [29]:
one . argmin()

0

In [30]:
one . argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [32]:
ar .argmin()

8

In [34]:
ar . argmax()

6

In [35]:
ar . argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [36]:
ar . argmax(axis=1)

array([2, 2, 0], dtype=int64)